### ISSUE TITLE
Could not determine Linux distro information - Amazon Linux (AWS EC2)

### ISSUE THREAD

**Issue by aly-saleh** [ianmiell/shutit_copyserver#2]
I am using amazon linux and I got this error:
Pause point on fail: Could not determine Linux distro information. Please inform ShutIt maintainers.

Amazon EC2 stock AMI with latest update:
https://aws.amazon.com/amazon-linux-ami/2016.03-release-notes/

**Comment by ianmiell** [comment]
I believe this should be fixed now.
